Update deploy

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -3,85 +3,64 @@ startDeploy()
 # Create a new task definition for this build
 
 sed -e "s;GIT_COMMIT;${IMAGE_VERSION};g" ${JSON_FILE}.json > ${JSON_FILE}-new-${BUILD_NUMBER}.json
+
 sed -e "s;GROUP_NAME;${GIT_BRANCH};g" ${JSON_FILE}-new-${BUILD_NUMBER}.json > ${JSON_FILE}-${BUILD_NUMBER}.json
+
 
 cat ${JSON_FILE}-${BUILD_NUMBER}.json
 
-aws ecs register-task-definition \
---family ${TASK_FAMILY} \
---cli-input-json file://${JSON_FILE}-${BUILD_NUMBER}.json \
---region eu-north-1 --profile testuser
+aws ecs register-task-definition --family ${TASK_FAMILY} --cli-input-json file://${JSON_FILE}-${BUILD_NUMBER}.json --cli-input-json file://${JSON_FILE}-${BUILD_NUMBER}.json --region eu-north-1 --profile testuser
 
-# Get latest revision (optional but kept)
-TASK_REVISION=$(aws ecs describe-task-definition \
---task-definition ${TASK_FAMILY} \
---region eu-north-1 --profile testuser \
-| egrep "revision" | tr "/" " " | awk '{print $2}' | sed 's/"$//')
-
+# Update the service with the new task definition and desired count
+TASK_REVISION=`aws ecs describe-task-definition --task-definition ${TASK_FAMILY} --region eu-north-1 --profile testuser | egrep "revision" | tr "/" " " | awk '{print $2}' | sed 's/"$//'`
 echo $TASK_REVISION
+DESIRED_COUNT=`aws ecs describe-services --cluster ${CLUSTER} --services ${SERVICE_NAME}  --region eu-north-1 --profile testuser | egrep "desiredCount" | tr "/" " " | awk '{print $2}' | sed 's/,$//'`
+echo $DESIRED_COUNT
+OLD_TASK_ID=$(aws ecs list-tasks --cluster ${CLUSTER} --desired-status RUNNING --service ${SERVICE_NAME} --region eu-north-1 --profile testuser | egrep "task/" | sed -E "s/.*task\/(.*)\"/\1/")
 
-# Deploy
-aws ecs update-service \
---cluster ${CLUSTER} \
---service ${SERVICE_NAME} \
---desired-count 1 \
---task-definition ${TASK_FAMILY} \
---force-new-deployment \
---region eu-north-1 --profile testuser
+aws ecs update-service --cluster ${CLUSTER} --service ${SERVICE_NAME} --desired-count 1 --task-definition ${TASK_FAMILY} --force-new-deployment --region eu-north-1 --profile testuser
 
-# Wait until stable
-aws ecs wait services-stable \
---cluster ${CLUSTER} \
---services ${SERVICE_NAME} \
---region eu-north-1 --profile testuser
-
-if [ $? -eq 0 ]; then
-  echo "Build got deployed successfully"
-else
-  echo "Build failed"
-  exit 1
+# Jenkins Job wait until service is avaliable in cluster
+aws ecs wait services-stable --cluster ${CLUSTER} --services ${SERVICE_NAME} --region eu-north-1 --profile testuser
+if [ $? -eq 0 ]; then 
+echo "Docker build got success"
+else 
+echo "Docker build was failed"
+exit 1
 fi
-
 rm -rf ${JSON_FILE}-${BUILD_NUMBER}.json
+rm -rf ${JSON_FILE}-new-${BUILD_NUMBER}.json
 }
 
-# Branch logic (kept as-is)
-if [ "$GIT_BRANCH" = "master-migration" ]
-then
-SERVICE_NAME="adfarm-tfw-web-migration"
-IMAGE_VERSION="${GIT_BRANCH}-${BUILD_NUMBER}"
-TASK_FAMILY="adfarm-tfw-web-migration"
-CLUSTER="production-tfw"
-JSON_FILE="adfarm-tfw-web-mig"
-startDeploy
 
+if [ "$GIT_BRANCH" = "development" ]
+then
+SERVICE_NAME="dev-sandbox-service"
+IMAGE_VERSION="${GIT_BRANCH}-${BUILD_NUMBER}"
+TASK_FAMILY="dev-sandbox-service"
+CLUSTER="dev-oralia"
+START_CMD="start"
+JSON_FILE="oralia-sandbox-dev"
+startDeploy
 elif [ "$GIT_BRANCH" = "main" ]
 then
-SERVICE_NAME="my-service-1"
+SERVICE_NAME="cyber-service"
 IMAGE_VERSION="${GIT_BRANCH}-${BUILD_NUMBER}"
-TASK_FAMILY="my-task"
-CLUSTER="my-cluster"
+TASK_FAMILY="cyber"
+CLUSTER="earth"
+START_CMD="start"
 JSON_FILE="taskdef"
 startDeploy
-
-elif [ "$GIT_BRANCH" = "preprod" ]
+elif [ "$GIT_BRANCH" = "uat" ]
 then
-SERVICE_NAME="preprod-adfarm-tfw-web"
+SERVICE_NAME="uat-generic-chatbot-services"
 IMAGE_VERSION="${GIT_BRANCH}-${BUILD_NUMBER}"
-TASK_FAMILY="adfarm-tfw-web"
-CLUSTER="development-tfw"
-JSON_FILE="adfarm-tfw-web"
+TASK_FAMILY="dev-generic-chatbot-services"
+CLUSTER="production"
+START_CMD="start"
+JSON_FILE="dev-generic-chatbot-services"
 startDeploy
-
-elif [ "$GIT_BRANCH" = "master" ]
-then
-SERVICE_NAME="adfarm-tfw-web"
-IMAGE_VERSION="${GIT_BRANCH}-${BUILD_NUMBER}"
-TASK_FAMILY="adfarm-tfw-web"
-CLUSTER="production-tfw"
-JSON_FILE="prod-adfarm-web"
-startDeploy
-
 else
-echo "Skipping deployment: ${GIT_BRANCH} not allowed"
+echo "Skipping a deployment because this branch is not permitted for docker deployment: ${GIT_BRANCH}"
+
 fi
