Update deploy

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -3,35 +3,49 @@ startDeploy()
 # Create a new task definition for this build
 
 sed -e "s;GIT_COMMIT;${IMAGE_VERSION};g" ${JSON_FILE}.json > ${JSON_FILE}-new-${BUILD_NUMBER}.json
-
 sed -e "s;GROUP_NAME;${GIT_BRANCH};g" ${JSON_FILE}-new-${BUILD_NUMBER}.json > ${JSON_FILE}-${BUILD_NUMBER}.json
-
 
 cat ${JSON_FILE}-${BUILD_NUMBER}.json
 
-aws ecs register-task-definition --family ${TASK_FAMILY} --cli-input-json file://${JSON_FILE}-${BUILD_NUMBER}.json --region eu-north-1 --profile testuser
+aws ecs register-task-definition \
+--family ${TASK_FAMILY} \
+--cli-input-json file://${JSON_FILE}-${BUILD_NUMBER}.json \
+--region eu-north-1 --profile testuser
 
-# Update the service with the new task definition and desired count
-TASK_REVISION=`aws ecs describe-task-definition --task-definition ${TASK_FAMILY} --region eu-north-1 --profile testuser | egrep "revision" | tr "/" " " | awk '{print $2}' | sed 's/"$//'`
+# Get latest revision (optional but kept)
+TASK_REVISION=$(aws ecs describe-task-definition \
+--task-definition ${TASK_FAMILY} \
+--region eu-north-1 --profile testuser \
+| egrep "revision" | tr "/" " " | awk '{print $2}' | sed 's/"$//')
+
 echo $TASK_REVISION
-DESIRED_COUNT=`aws ecs describe-services --cluster ${CLUSTER} --services ${SERVICE_NAME}  --region eu-north-1 --profile testuser | egrep "desiredCount" | tr "/" " " | awk '{print $2}' | sed 's/,$//'`
-echo $DESIRED_COUNT
-OLD_TASK_ID=$(aws ecs list-tasks --cluster ${CLUSTER} --desired-status RUNNING --service ${SERVICE_NAME} --region eu-north-1 --profile testuser | egrep "task/" | sed -E "s/.*task\/(.*)\"/\1/")
-echo $OLD_TASK_ID
-aws ecs stop-task --cluster ${CLUSTER} --task ${OLD_TASK_ID} --region us-east-1 --profile tfw-new
-aws ecs update-service --cluster ${CLUSTER} --service ${SERVICE_NAME} --desired-count 1 --task-definition ${TASK_FAMILY} --force-new-deployment --region eu-north-1 --profile testuser
 
-# Jenkins Job wait until service is avaliable in cluster
-aws ecs wait services-stable --cluster ${CLUSTER} --services ${SERVICE_NAME} --region eu-north-1 --profile testuser
+# Deploy
+aws ecs update-service \
+--cluster ${CLUSTER} \
+--service ${SERVICE_NAME} \
+--desired-count 1 \
+--task-definition ${TASK_FAMILY} \
+--force-new-deployment \
+--region eu-north-1 --profile testuser
+
+# Wait until stable
+aws ecs wait services-stable \
+--cluster ${CLUSTER} \
+--services ${SERVICE_NAME} \
+--region eu-north-1 --profile testuser
+
 if [ $? -eq 0 ]; then
-echo "Build got deployed successfully"
+  echo "Build got deployed successfully"
 else
-echo "Build failed"
-exit 1
+  echo "Build failed"
+  exit 1
 fi
+
 rm -rf ${JSON_FILE}-${BUILD_NUMBER}.json
 }
 
+# Branch logic (kept as-is)
 if [ "$GIT_BRANCH" = "master-migration" ]
 then
 SERVICE_NAME="adfarm-tfw-web-migration"
@@ -40,6 +54,7 @@ TASK_FAMILY="adfarm-tfw-web-migration"
 CLUSTER="production-tfw"
 JSON_FILE="adfarm-tfw-web-mig"
 startDeploy
+
 elif [ "$GIT_BRANCH" = "main" ]
 then
 SERVICE_NAME="my-service-1"
@@ -48,6 +63,7 @@ TASK_FAMILY="my-task"
 CLUSTER="my-cluster"
 JSON_FILE="taskdef"
 startDeploy
+
 elif [ "$GIT_BRANCH" = "preprod" ]
 then
 SERVICE_NAME="preprod-adfarm-tfw-web"
@@ -56,6 +72,7 @@ TASK_FAMILY="adfarm-tfw-web"
 CLUSTER="development-tfw"
 JSON_FILE="adfarm-tfw-web"
 startDeploy
+
 elif [ "$GIT_BRANCH" = "master" ]
 then
 SERVICE_NAME="adfarm-tfw-web"
@@ -64,6 +81,7 @@ TASK_FAMILY="adfarm-tfw-web"
 CLUSTER="production-tfw"
 JSON_FILE="prod-adfarm-web"
 startDeploy
+
 else
-echo "Skipping a deployment because this branch is not permitted for docker deployment: ${GIT_BRANCH}"
+echo "Skipping deployment: ${GIT_BRANCH} not allowed"
 fi
